apps/org/tests/test_views.py, apps/org/views.py
If the request to create a user in VMI succeeds (during step 1 of the member-creation process), the code in `smh_app` also creates a `ResourceRequest` from the relevant `Organization` for the new `Member`'s data.
=> Organization User Creates Member Step 1 Background

apps/org/tests/test_views.py, apps/org/views.py
This pull request updates the code so that when a new member sets their password (in the last step of the member creation process), the password gets set in VMI.
=> New Member Sets Password In VMI

.docker/Dockerfile
implements [issue#70](https://github.com/TransparentHealth/smh_app/issues/70). 
If this is correct, the build process should work correctly, and the assets (css and js) will be built during deployment.
=> Make assets when building app container

apps/org/templates/org/org_create_member.html, apps/org/views.py, assets/package-lock.json, assets/sass/components/Modal/_modal.scss
This PR is connected with [VMI PR #119](https://github.com/TransparentHealth/vmi/pull/119), which deals with situations where the username already exists.
Here, we deal with the display of the general error message in the form.
* Put general error messages in an error div above the form.
* In the view, use cleaned form data where possible.
* Give the user a random uuid4() temporary password rather than something even moderately guessable.
* Clean up the template + css for modal / form – use bootstrap more.
=> Create User: deal with existing username

apps/member/templates/member_tabbed_nav.html, apps/member/templates/providers.html, apps/member/templates/summary.html, apps/member/urls.py, apps/member/views.py
The api endpoint that we are using is literally `https://gist.githubusercontent.com/aviars/266ea80129819af9f0b83835bf78bfef/raw/493d8dbda82b923dce8c0ffdca8e8b79e76a47ba/hixny-everything-sample.json`.  In the providers tab the doctor currently in there with encounters most often is `DOCTOR OTHER` If we need to display something a little nicer, we can change the `ecounter['participant']` to be a different provider.
=> summary & providers tabs

apps/member/utils.py
Fetch HIXNY data from the sharemyhealth API with a request to refresh it, and memoize for a minute for a modicum of sanity.
=> Fetch hixny data live

.development/Dockerfile, apps/member/templates/member/dashboard.html, assets/sass/components/MemberTabs/MemberOrgs/_member-orgs.scss, assets/sass/components/MemberTabs/_member_dashboard.scss
Fix a couple of style and build issues with org / member logos
=> Member orgs 2

.gitignore, apps/member/tests/test_views.py, apps/member/views.py, requirements.txt, setup.cfg, test.sh
Added tests for Member Organizations page, and created a basic testing harness that includes coverage in a bid to begin improving unit test coverage in smh_app.
=> Member orgs testing

apps/org/templates/org/member_complete.html, apps/org/tests/test_views.py, apps/org/views.py, assets/sass/components/Modal/_modal.scss, setup.cfg
During Org Create Member Complete,
* ensure ResourceGrant and org association
* redirect to /, which goes to the appropriate dashboard or login for the current browser.
This requires that https://github.com/TransparentHealth/vmi/pull/140 be merged as well.
=> Org create member with ResourceGrant

apps/member/utils.py, apps/member/views.py
Re-introduces @memoize on fetch_member_data from sharemyhealth
=> Reintroduce memoize cache

apps/member/views.py
This only implements/fixes the provider listing — not the individual provider details.
=> Make providers tab work – basic listing

apps/member/pipeline.py, apps/member/templates/data_sources.html, apps/member/utils.py, apps/member/views.py, apps/notifications/views.py, apps/users/models.py, apps/users/pipeline/oidc.py, setup.cfg, smh_app/settings.py, tox.ini
After connecting to sharemyhealth (hixny api), dismiss the notification to do so.
=> Notifications after connect

.development/Dockerfile, apps/member/pipeline.py, apps/org/models.py, smh_app/settings.py
Add a notification when member connects to Hixny, dismiss those notifications when they disconnect.
=> Notify hixny connect disconnect

.travis.yml, apps/data/admin.py, apps/data/apps.py, apps/data/models/__init__.py, apps/data/models/allergy.py, apps/data/models/model.py, apps/data/models/types.py, apps/data/tests.py, apps/data/util.py, apps/data/views.py, apps/member/constants.py, apps/member/urls.py, apps/member/utils.py, apps/member/views.py, requirements.txt, smh_app/settings.py, tox.ini
UPGRADE TO PYTHON 3.7 to use the spiffy new built-in python dataclasses 
New "data" app (apps.data) holds models for FHIR STU3 data. Eventually these can be converted / fed into Django models.
"Prescriptions" in Medical Records.
=> Data models

apps/org/templates/org/member_almost_done.html, apps/users/views.py
... when clicking the link to set password and authorize org.
=> Logout after member creation

.gitignore, apps/member/utils.py, apps/member/views.py
If fetch_member_data() results in 403, that means we have a token that expired. So redirect these fetch_member_data() requests to re-authorize to the sharemyhealth API.
=> Re-authorize to sharemyhealth

apps/member/templates/records.html, apps/member/utils.py, apps/member/views.py, assets/sass/App.scss
* new "debug-panel" css class
* add data from hixny to medical records context if DEBUG
* display auth error to sharemyhealth
* display hixny connect errors
=> Debug reporting in medical data

apps/member/utils.py
If the access_token has expired, try using the refresh_token to refresh it.
=> Medical Data Refresh Token

apps/member/utils.py, apps/org/views.py, apps/users/utils.py, apps/users/views.py, smh_app/settings.py
Added refresh token to org Create Member workflow
=> Refresh token org create member

apps/member/templates/member.html, apps/member/templates/member/dashboard.html, apps/member/templates/member_sidebar.html, apps/member/tests/test_views.py, apps/org/models.py, apps/org/templates/org/dashboard.html, apps/org/tests/test_views.py, apps/org/views.py, apps/users/models.py, apps/users/tests/test_models.py, apps/users/tests/test_views.py, templates/header.html
User.profile property – now the primary interface to the User.userprofile object. User.profile creates User.userprofile if it doesn't exist, returns User.userprofile object.
=> User.profile property

apps/member/views.py
Fixes a bug in the prescriptions display that prevents display of prescription details in the pop up.
=> Fix string formatting error

apps/data/models/__init__.py, apps/data/models/observation.py, apps/data/models/types.py, apps/member/views.py, assets/package-lock.json, requirements.txt, smh_app/load_env.py
Fixing the display of Lab Results, and making it more robust by using the Observation data model to deserialize from fhir.
=> Lab Results view with Observation data model

apps/data/models/encounter.py, apps/data/models/practitioner.py, apps/data/models/prescription.py, apps/data/models/types.py, apps/member/templates/member_tabbed_nav.html, apps/member/templates/provider_details.html, apps/member/templates/providers.html, apps/member/urls.py, apps/member/utils.py, apps/member/views.py, apps/users/tests/test_views.py, apps/users/views.py, assets/sass/App.scss, assets/sass/components/_practitioner.scss, assets/sass/styles/_variables.scss
This is a first draft, better Providers list and new Provider details page.
=> Provider details

apps/member/templates/member.html, apps/org/forms.py, apps/org/templates/org/member_basic_info.html, apps/org/templates/org/member_verify_identity.html, apps/users/models.py, templates/modal_base.html
* Date picker on Create Member modals
* Basic Info / birthdate
* Verify Identity / exp
* Long-format dates on member details page 
* birthdate
* member since
=> Date picker, date formats

assets/package-lock.json, assets/package.json
I just ran `npm audit fix`. Still need to do a more comprehensive front-end review.
=> npm audit fix – deal with the majority of the vulnerabilities

apps/member/templates/member_tabbed_nav.html, apps/member/templates/providers.html, apps/member/templates/records.html, apps/member/templates/summary.html, apps/member/templates/time_since_update.html, apps/member/urls.py, apps/member/utils.py, apps/member/views.py
Provide a new interface by which to prompt members to update their health data, and use the new sharemyhealth data interface.
=> Limit hixny data calls

smh_app/middleware.py, smh_app/settings.py
This works both for auth to VMI (not yet logged in) and for authorizing SMH (home redirects to dashboard, nevermind).
=> Redirect to home if AuthCanceled. 

apps/member/views.py
Label diagnosis description as "Diagnosis", and display it first in the list.
=> Fix Diagnoses display

apps/org/views.py
– VMI will generate one for us (once the companion branch is merged)
NOTE: The same-named branch on VMI should be merged before this one.
=> Allow posting a blank user email address to VMI

apps/users/models.py
new rule: All users who are not UserType.ORG_AGENT are UserType.MEMBER
=> No "Other" members

apps/common/templatetags/fhirtags.py, apps/member/constants.py, apps/member/fhir_custom_formats.py, apps/member/fhir_utils.py, apps/member/views_new.py
Filter Providers on Identifier
=> Add Metric to US Conversion with Precision
